services:
  database.drobot-vlad.com:
    image: postgres:16.1
    environment:
      POSTGRES_USER: vlad
      POSTGRES_PASSWORD: drobot
      POSTGRES_DB: supply_department
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: bind
        source: ./supply_department_db_data
        target: /var/lib/postgresql/data

  djangoapp.drobot-vlad.com:
      build:
        context: .
        dockerfile: supply_department/Dockerfile
      depends_on:
        database.drobot-vlad.com:
          condition: service_started
      ports:
        - 8822:8000

  db_manipulation.env.drobot-vlad.com:
    build:
      context: .
      dockerfile: db_manipulation/Dockerfile
    volumes:
      - ./db_manipulation/scripts:/db_manipulation
    depends_on:
      database.drobot-vlad.com:
        condition: service_started
    entrypoint: ["echo", "Control panel ready!"]

  pgadmin:
    image: dpage/pgadmin4:8.13.0
    container_name: pgadmin
    ports:
      - 8811:80
    environment:
      PGADMIN_DEFAULT_EMAIL: drobotvlad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: drobot
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
